### ISSUE TITLE
Using socketlib in a macro

### ISSUE THREAD

**Issue by bogga** [manuelVo/foundryvtt-socketlib#19]
Hi,

This is less an issue and more a request for advice.

I'm trying to write a macro to allow a player to roll healing and automatically apply said healing to another player's actor without giving them the owner permission (for the other actor[s]) the system wants them to have.

I'm struggling with setting up socketlib, I was hoping I'd be able to set the socket up in the macro but I'm not sure that works as I'm getting `socket is undefined` when running the macro. Here's the relevant bits:

```js
let socket;

Hooks.once("socketlib.ready", () => {
  socket = socketlib.registerModule("issie-healing-socket-module");
  socket.register("issieHealOrHarm", doHealing);
})

...

const doHealing = async (amount, victimActorId) => {
  const victim = game.actors.get(victimActorId);
  await victim.actor.applyDamage({ damage: amount, token: victim });
}

...

const foo = () => {
  await socket.executeAsGM("issieHarmOrHeal", -1 * finalAmount, victim.actor.id);
}
```

Do I need to create a module and then call an exposed method from that module in the macro instead? (And if so, do you have an example of what that would look like?)

**Comment by manuelVo** [comment]
Hi,

socketlib can only be used by modules and game systems, not by macros. The reason for this is that every client needs to register in socketlib to allow it to process messages sent by other clients. In macros, this cannot happen, because macros are only ever executed during gameplay. This means when your macro is being executed, the Hooks.once-event has already happened. So registering that hook no longer has any effect.

In general, your code looks fine (howevery `victim` is undefined in `foo` which will cause issues). All you need to do is to put that code into a module and to make the function `foo` accessible for macros (by attaching it to an appropriate entity, for example to the window, to an actor, etc.).

However, if you need to create a module anyway, it might be worthwhile to not do a macro but do a module that takes care of the functionality instead of exposing a function and then writing a macro that makes use of that function.

**Comment by bogga** [comment]
gotcha! Thanks for the advice, I've set up a basic module that exposes a function for the macro to run (in `window.adam.funcname` - might not be best practises but it works!)
