### ISSUE TITLE
Synchronize with Lancer Clocks

### ISSUE THREAD

**Issue by danielmacapa** [manuelVo/foundryvtt-socketlib#7]
Sorry, it´s was a wrong. I don't know how delete the post.

**Comment by manuelVo** [comment]
There's no way to delete posts. This is to prevent people from getting confused because stuff is gone all of the sudden (imagine me trying to find that issue that github sent me a notification mail about, if it was gone). Just closing the issue and leaving a short statement that it doesn't actually exist is fine :)
